# Core site settings ----------------------------------------------------------
title: blank
first_name: Robin
middle_name: Inho
last_name: Kee
email: inhokee@umich.edu
description: Personal website of Robin Inho Kee
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
lang: en
icon: favicon.png

url: https://signalkee.github.io
baseurl:
last_updated: false
impressum_path:
back_to_top: true

# Layout ----------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
max_width: 1120px
enable_darkmode: true

# Public profiles -------------------------------------------------------------
github_username: signalkee
linkedin_username: inhokee
scholar_userid: XHe7apIAAAAJ

# Metadata --------------------------------------------------------------------
keywords:
serve_og_meta: false
serve_schema_org: false
og_image:

# Content ---------------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

jekyll-minifier:
  exclude: ["robots.txt"]
  uglifier_args:
    harmony: true

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

lazy_loading_images: true

# Third-party library used by Bootstrap 4 ------------------------------------
third_party_libraries:
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"
    version: "3.6.0"
