name: Check for broken links

on:
  push:
    branches: [master, main]
    paths:
      - "_data/**"
      - "_includes/**"
      - "_layouts/**"
      - "_pages/**"
      - "_projects/**"
      - "assets/**"
      - "*.html"
      - "*.md"
      - "*.yml"
  pull_request:
    branches: [master, main]
    paths:
      - "_data/**"
      - "_includes/**"
      - "_layouts/**"
      - "_pages/**"
      - "_projects/**"
      - "assets/**"
      - "*.html"
      - "*.md"
      - "*.yml"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --user-agent 'curl/7.54' --exclude-path README.md --exclude-path _pages/404.md --verbose --no-progress './**/*.md' './**/*.html'
