name: Prettier code formatter

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install formatting dependencies
        run: npm ci
      - name: Prettier check
        run: npx prettier . --check
